### ISSUE TITLE
起動できないDRM保護ゲーム「水平線まで何マイル？」

### ISSUE THREAD

**Issue by kotobukit** [fa0311/DMMGamePlayerFastLauncher#102]
### OS

Windows10 22H2

### 不具合の説明

DMMGamePlayerFastLauncher Version: **v5.1.2**
タイトル: 水平線まで何マイル？ −Deep Blue Sky ＆ Pure White Wings− Windows10対応版
URL: https://dlsoft.dmm.co.jp/detail/tin_0001/

エラーメッセージが出ず、デバッグログも出力中に勝手に閉じてしまうので貼れるものがありません。
直前のデバッグログがどこかのパスに吐かれる仕様でしたら、該当のパスを教えていただければ貼らせていただきます。
もしくはv5.2.0でデバッグログが閉じなくなるようなのでリリースを待って再度デバッグログを貼らせていただきます。

**Comment by kotobukit** [comment]
v5.2.0(#99 )で正常に起動できました。
なお、以前と変わらず起動前にデバッグウィンドウは消えます。

**Comment by fa0311** [comment]
起動前にデバッグウィンドウは消えるのはどうしようもなさそうですね
状況から察するにゲームを実行するexeが実行されるとゲームが別のプロセスで立ち上がって最初に起動したプロセスが終了してそうです
後から起動されたプロセスをランチャーから追うのは大変な上にメリットが何もなさそうなので対応しません

起動前にデバッグウィンドウは消えた場合でも意図した挙動はされていると思います
