### ISSUE TITLE
ショートカット作成のファイル名を日本語にすると起動しない

### ISSUE THREAD

**Issue by komrasaki** [fa0311/DMMGamePlayerFastLauncher#113]
### OS

Windows 11

### 不具合の説明

高速起動を行うショートカット作成時にファイル名を日本語にし、ショートカットからアプリを起動しようとするとエラーとなり起動できない。
ファイル名が英語のみの場合、問題なく起動した。
(ひらがなやカタカナによって動作が変わってくるので文字コードなどが影響している？)
また、混在パターンも試してみた結果も記載します。

ファイル名：あいうえお
`特に何も起こらない
アプリも起動しなければエラーも出ない`

ファイル名：aあ
`Traceback (most recent call last):
  File "launch.py", line 41, in thread
  File "launch.py", line 51, in launch
FileNotFoundError: [Errno 2] No such file or directory: 'data\\shortcut\\豁｣.json'`

ファイル名：aア
`Traceback (most recent call last):
  File "launch.py", line 41, in thread
  File "launch.py", line 51, in launch
FileNotFoundError: [Errno 2] No such file or directory: 'data\\shortcut\\a繧｢.json''`

ファイル名：あa
`Traceback (most recent call last):
  File "launch.py", line 41, in thread
  File "launch.py", line 51, in launch
FileNotFoundError: [Errno 2] No such file or directory: 'data\\shortcut\\縺Ｂ.json'`

ファイル名：アa
`Traceback (most recent call last):
  File "launch.py", line 41, in thread
  File "launch.py", line 51, in launch
FileNotFoundError: [Errno 2] No such file or directory: 'data\\shortcut\\繧｢a.json''`

ファイル名：ア
`Traceback (most recent call last):
  File "launch.py", line 41, in thread
  File "launch.py", line 51, in launch
FileNotFoundError: [Errno 2] No such file or directory: 'data\\shortcut\\繧｢.json'`

ファイル名：正
`Traceback (most recent call last):
  File "launch.py", line 41, in thread
  File "launch.py", line 51, in launch
FileNotFoundError: [Errno 2] No such file or directory: 'data\\shortcut\\豁｣.json'`

**Comment by fa0311** [comment]
報告ありがとうございます、ファイル名に日本語は使わないでください
前はどこかに表記されていたのですが何らかのタイミングで消したままになっていました

**Comment by fa0311** [comment]
注釈を追加した

**Comment by komrasaki** [comment]
ファイルが修正されていることは確認できたのですが、実際に起動して確認してみるとツールチップの表示行数が2行の為追加したメッセージが表示されておらず・・・

`入力必須項目です。`
`このショートカットに任意の名前を付けてください。`
`半角英数字以外を使用すると問題が発生する可能性があります。`(←これが表示されていない)

**Comment by fa0311** [comment]
アップデート対応がガバガバでした。

一時対応として
過去に使用していた言語ファイル (`app.en.yml`, `app.ja_JP.yml`) が `DMMGamePlayerFastLauncher\assets\i18n` に残っているためそれを削除してください。
または、２つある `日本語` のうち、もう片方のものにすれば解消されます。
![image](https://github.com/fa0311/DMMGamePlayerFastLauncher/assets/34892635/7a758eae-05ae-4175-ad65-03389345ea5d)

**Comment by komrasaki** [comment]
ありがとうございます！
確認できました！

**Comment by fa0311** [comment]
v5.4.1 で修正しました👍
