### ISSUE TITLE
"DMM session has expired"エラーが出る

### ISSUE THREAD

**Issue by runealt** [fa0311/DMMGamePlayerFastLauncher#116]
ショートカットからゲームを起動しようとすると以下のエラーが出る。ショートカットを修正しようとしても同様のエラーが出てショートカットの編集に失敗する。

```
Traceback (most recent call last):
  File "tab\shortcut.py", line 127, in save_callback
  File "tab\shortcut.py", line 156, in get_game_info
Exception: DMM session has expired
```

**Comment by runealt** [comment]
上記自己解決しました。

1. アカウントをDMMGamePlayerからインポートをする
2. DMMGamePlayerの高速起動を行なうショートカットを作成する
3. ゲームの高速起動を行なうショートカットを作成する

以上の手順でアカウント設定から作り直すとショートカット作成できるようになりました。

おそらく長期間（1週間程度？）ログインが無かった場合の実行エラーと思われます。

**Comment by fa0311** [comment]
以下の手順に従ってください
- DMM Launcherを起動してログインし直す
- DMMGamePlayerFastLauncher でアカウントをインポートし直す

長期間ログインしなかったり、DMMGamePlayerFastLauncher にインポートしたDMMアカウントでDMM Launcherにログインをするとこのエラーが出る場合があります。
