### ISSUE TITLE
Mislabled DMM Proxy options

### ISSUE THREAD

**Issue by koma-cute** [fa0311/DMMGamePlayerFastLauncher#126]
### OS

Windows 10

### Bug Description

The DMM HTTP/HTTPS/SOCKS Proxy options are mislabeled. As described in https://requests.readthedocs.io/en/latest/user/advanced/#proxies - the key for the `proxies` dictionary corresponds to the protocol that the proxy should be applied to when making requests to servers of that type, not the type of the proxy itself. This results in the correct method of connecting to a proxy with the DMM options being to only use the "DMM HTTPS Proxy" option, as no requests are made over HTTP and `socks` is an invalid type. The value would then include the protocol (e.g. `socks5://localhost:9999`).

Relevant code:
https://github.com/fa0311/DMMGamePlayerFastLauncher/blob/33f261c9948778d5eab8b7c7b991025b086da97c/DMMGamePlayerFastLauncher/DMMGamePlayerFastLauncher.py#L68-L79

**Comment by fa0311** [comment]
It was my lack of research.
I don't really feel the need to separate proxies for each protocol, so I may as well set them all to `ALL_PROXY`.


```py
os.environ["ALL_PROXY"] = ...
DgpSessionV2.PROXY["all"] = ...
```
