### ISSUE TITLE
「ショートカットの作成」のファイル名は<product_id>_<account_name>で自動設定されたほうがよいのでは？

### ISSUE THREAD

**Issue by kotobukit** [fa0311/DMMGamePlayerFastLauncher#129]
### 機能を説明する

login requireに見舞われ1からインポート等しなおした時に
ファイル名に日本語を入れてしまい起動できず小一時間格闘したため(2敗)

現状の「ショートカット作成」画面は
* ファイル名
* product_idの選択
* アカウントの選択

となっていますが、順番を入れ替え

* product_idの選択
* アカウントの選択
* ファイル名

と並べ、上から順にproduct_idとアカウントをプルダウンメニューから選択することによって、
ファイル名欄に「<product_id>_<account_name>」と自動で埋まるのがよいのではと思っています。

例えば、
* product_id: **umamusume**
* アカウント: **kotobukit**

を選択した場合は、ファイル名欄に

* **umamusume_kotobukit**

と自動で埋められることとなります。

主語が大きすぎるとは思いますが、だいたいのユーザーは上記のような自動設定で事足りるのではと思っています。
自分で設定する方向けに自動で埋められても手入力できる状態のテキストエリアであれば問題ないかなと思う次第です。

**Comment by fa0311** [comment]
> ファイル名に日本語を入れてしまい起動できず小一時間格闘したため(2敗)

ツールチップに半角英数字についての注意事項を書いてあるはずですが、見落とす人が多いのであれば別のアプローチを追加した方が良さそうですね

> だいたいのユーザーは上記のような自動設定で事足りるのではと思っています。

自分の場合、同一ゲームを「通常起動のショートカット」と「フルスクリーンで起動するショートカット」を使い分けているんですが、少数派でしょうか？？

---

自動入力はユーザーが混乱する原因になると思うので実装はしません
そもそも、日本語を含む場合でも正常に起動できるようにするか、半角英数字以外の文字列の入力を禁止するべきだとは自分も思います

**Comment by fa0311** [comment]
> 確かにそのような実装の方がよさそうですね

5.6.1 で修正したのでcloseします
