### ISSUE TITLE
明朝体が勝手にロードされる

### ISSUE THREAD

**Issue by reindex-ot** [fa0311/DMMGamePlayerFastLauncher#133]
### OS

Windows 11 23H2

### 不具合の説明

インストールされている明朝体がUI上に表示されてしまう。
他のPythonなアプリケーション([MIO-KITCHEN](https://github.com/ColdWindScholar/MIO-KITCHEN-SOURCE))でも同様の現象が起きているのでTkinter側の問題の可能性が強いようです。
![DMM](https://github.com/fa0311/DMMGamePlayerFastLauncher/assets/32851879/9d92fa11-797e-40e1-ab01-daf59d5fbb6d)
![MIO](https://github.com/fa0311/DMMGamePlayerFastLauncher/assets/32851879/c17a5032-129f-459a-b46a-0594e14649cd)

**Comment by reindex-ot** [comment]
一応

````
import tkinter.font

...

tkinter.font.nametofont("TkDefaultFont").configure(family='Yu Gothic UI')

xxx.mainloop()
````

**Comment by fa0311** [comment]
@reindex-ot 
問題が再現できないので以下をお願いしたいです。

1. DMMGamePlayerFastLauncher で `設定 -> テーマ` を `blue` に設定
1. `.\DMMGamePlayerFastLauncher\assets\themes` 内の `blue.json` をエディタ等で開く
1. `CTkFont -> Windows -> family` を `Yu Gothic UI` にしてランチャーを再起動

**Comment by fa0311** [comment]
`assets\themes` 内のテーマ設定を無視するように変えた。
`設定 -> OSフォントの利用を強制する` のチェックを外せば無効化出来るが、デフォルトでは有効。

先程のコメントの手段を試して、改善するようであれば [4811ef7](https://github.com/fa0311/DMMGamePlayerFastLauncher/commit/4811ef79a9db4f4cb3ce59da4921dcbb7ee0ece8) の変更で解決するはず。

**Comment by fa0311** [comment]
言語ごとにデフォルトのフォントが変わるように変更した。
https://github.com/fa0311/DMMGamePlayerFastLauncher/commit/3ce821b7f86b9bc3263cca2418cb968644f526c4#diff-177f61a1c93df7b63173037c9a7ed46f11d00bccb3eff669a450ea5c91e89ba2R5-R7
日本語以外の言語も良い感じに切り替わるので良さそう

**Comment by reindex-ot** [comment]
無事にYu Gothinc UIのロードを確認しました。

**Comment by ookiineko** [comment]
> https://github.com/ColdWindScholar/MIO-KITCHEN-SOURCE/pull/51/files そもそも、`TkDefaultFont` の値が信用できないっぽい？

sorry for the confusion! ><

as you already knew, TkDefaultFont should be just in the right ui font family appropriate for the system language (i think, unless changed using noMeiryoUI),

the code in my PR was wrong. for the specific case in MIO kitchen (which uses sv_ttk instead of CTk), see also: https://github.com/ColdWindScholar/MIO-KITCHEN-SOURCE/issues/8#issuecomment-2153731017

**Comment by fa0311** [comment]
@ookiineko 
Thanks for reporting back!


This software has already changed to provide multiple font options, so a revert should not be necessary.
