### ISSUE TITLE
tutorial / チュートリアル

### ISSUE THREAD

**Issue by fa0311** [fa0311/DMMGamePlayerFastLauncher#135]
https://github.com/fa0311/DMMGamePlayerFastLauncher/assets/34892635/1dcccc2b-0f18-4d27-bab4-5e1af4beb31d

**Comment by fa0311** [comment]
1. `0:18`: 動画のようにチェックボックスをチェックしてください。
1. `0:31`: DMM Game Playerのプロセスが実行されていないことを確認してください。
1. `0:43`: アカウントをインポートしてください。
1. `0:50`: 新しいDMM Game Playerのショートカットを作成してください。
1. `1:05`: 古いDMM Game Playerのショートカットを削除してください。
    - 他のアカウントでインポートする場合を除き、古いショートカットでログインしないでください。
    - 間違いを避けるために削除することをお勧めします。
1. `1:12`: 新しいショートカットで正常に起動できるか確認してください。
1. `1:27`: Memento-moriのショートカットを作成してください。
1. `1:42`: 古いMemento-moriのショートカットを削除してください。
    - ゲームを起動する際にDMM Game Playerが作成したショートカットは使用しないでください。
1. `1:50`: ゲームが正常に起動しました。

---
1. `0:18`: Check the boxes as shown in the video.
1. `0:31`: Ensure the DMM Game Player process is not running.
1. `0:43`: Import your account.
1. `0:50`: Create a new DMM Game Player shortcut.
1. `1:05`: Remove the old DMM Game Player shortcut.
    - Do not log in with the old shortcut unless you are importing with another account.
    - It is recommended to delete it to avoid mistakes.
1. `1:12`: Check if you can start using the new shortcut.
1. `1:27`: Create a shortcut to Memento-mori.
1. `1:42`: Remove the old Memento-mori shortcut.
    - Do not use shortcuts created by the DMM Game Player to launch games.
1. `1:50`: The game has started successfully.

**Comment by TheOppaiDragon** [comment]
Can you make tutorial how to connect proxy into DMMGamePlayer? Or how to implement openvpn connection inside our launcher

**Comment by fa0311** [comment]
[v5.9.0](https://github.com/fa0311/DMMGamePlayerFastLauncher/releases/tag/v5.9.0) によって追加されたブラウザから認証情報を抽出する機能はほとんどのログインに関する問題を解消します。
DMMGamePlayerからログイン情報を抽出していましたが、DMMGamePlayerは大雑把にログイン情報を管理するため不具合が多発していました。
ブラウザからログイン情報を抽出することによって全てが解決しますが、新しい試みなため予期しない不具合が発生する場合があります。
また、Socket5などのプロキシには対応しておらず、VPNを使用する必要があります。

---

The feature to extract authentication information from the browser, added in [v5.9.0](https://github.com/fa0311/DMMGamePlayerFastLauncher/releases/tag/v5.9.0), resolves most login-related issues.  
Previously, login information was extracted from DMMGamePlayer, but due to its loose management of login data, many issues occurred.  
Extracting login information directly from the browser resolves all these problems; however, as this is a new approach, unexpected bugs may occur.  
Additionally, it does not support proxies like Socket5, so you will need to use a VPN.

---

通过 [v5.9.0](https://github.com/fa0311/DMMGamePlayerFastLauncher/releases/tag/v5.9.0) 添加的从浏览器提取认证信息的功能解决了大多数与登录相关的问题。  
此前，登录信息是从DMMGamePlayer中提取的，但由于DMMGamePlayer对登录信息管理较为松散，导致了许多问题。  
直接从浏览器提取登录信息可以解决所有这些问题，但由于这是一个新的尝试，可能会出现一些意想不到的错误。  
此外，不支持Socket5等代理，因此需要使用VPN。

---

透過 [v5.9.0](https://github.com/fa0311/DMMGamePlayerFastLauncher/releases/tag/v5.9.0) 新增的從瀏覽器提取認證資訊功能解決了大多數與登入相關的問題。  
此前，登入資訊是從DMMGamePlayer中提取的，但由於DMMGamePlayer對登入資訊的管理較為鬆散，導致了許多問題。  
直接從瀏覽器提取登入資訊可以解決所有這些問題，但由於這是一個新的嘗試，可能會出現一些意料之外的錯誤。  
此外，不支援Socket5等代理，因此需要使用VPN。
