### ISSUE TITLE
Can't create a shortcut - `login required`

### ISSUE THREAD

**Issue by Quintasan** [fa0311/DMMGamePlayerFastLauncher#137]
### OS

Windows 11 Pro 22H2 22621.3737

### Bug Description

When I press any of the `Create shortcut` buttons, the app stops responding for a few seconds, then it creates a shortcut on my desktop but fails.

1. I **can** start DMMGamePlayer using the shortcut I created in `Shortcut -> Fast Launch GamePlayer`
2. `バックグラウンド実行を許可する` is unchecked

### Error Message

```Shell
Failed to retrieve game information
```

### Log

```Shell
Traceback (most recent call last):
  File "tab\shortcut.py", line 121, in fn
  File "tab\shortcut.py", line 185, in get_game_info
Exception: login required
```

**Comment by fa0311** [comment]
> I can start DMMGamePlayer using the shortcut I created in Shortcut -> Fast Launch GamePlayer

Does the software start while you are logged into DMM?

**Comment by Quintasan** [comment]
> Does the software start while you are logged into DMM?

@fa0311 I can start `DMMGamePlayer` using the shortcut created, and I can run Princess Connect Re:dive just fine

**Comment by fa0311** [comment]
Is this issue still occurring?
