### ISSUE TITLE
UAC自動昇格のショートカットが機能しない

### ISSUE THREAD

**Issue by tatsuya087** [fa0311/DMMGamePlayerFastLauncher#141]
[アイドルマスターシャイニーカラーズSong for Prism](https://dmg-shinycolors-song-for-prism.idolmaster-official.jp/)で、UAC自動昇格のショートカットを作成してもゲームが起動しません。手動昇格のショートカットの場合は起動しました。

また、試しに何度かショートカットを作り直していたとき、たまにエラー(下記)でショートカット自体が作られないことがありました。
```
Traceback (most recent call last):
  File "tab\shortcut.py", line 121, in fn
  File "tab\shortcut.py", line 185, in get_game_info
Exception: login required
```

**Comment by fa0311** [comment]
バグ報告ありがとうございます
自分の環境では動作しました
`login required` に起因する起動時のエラーかと思われます
