### ISSUE TITLE
アカウントのインポートができません

### ISSUE THREAD

**Issue by ryomaco514** [fa0311/DMMGamePlayerFastLauncher#144]
DMMGamePlayerFastLauncherを一度すべて削除し再インストール後アカウントのインポート行ったところ、
以下のエラーで進むことができませんでした。
Traceback (most recent call last):
  File "lib\toast.py", line 18, in _wrapper
  File "tab\account.py", line 78, in callback
  File "lib\DGPSessionV2.py", line 126, in read
sqlite3.OperationalError: Could not decode to UTF-8 column 'encrypted_value' with text 'v10��$1��O�3�0�2,�H���b_'����]2<�o"?b����'

**Comment by fa0311** [comment]
#143 の重複としてCloseします

**Comment by ryomaco514** [comment]
ご対応くださりありがとうございます。
早速ダウンロードし再現の有無を確認したところ、恐縮ですが状況の変化はありませんでした。
手順は動画の通りDMMGamePlayerプロセスの終了を確認してインポートを行っています。
インストーラタイプ、Zip解凍のそれぞれで同じ現象を確認済みです。
最新のDMMGamePlayer5.3.13からDMMGamePlayer5.3.12へのダウングレードを行いリトライもしましたが、変化はありませんでした。
環境はWindows10です。
この度の報告に目を通してくださり重ねて御礼申し上げます。
何卒よろしくお願いいたします。

**Comment by fa0311** [comment]
発生するエラーメッセージも同じですか？

`インポートに失敗しました。` や `login required` の解決についてはこちらが原因かと思います
https://github.com/fa0311/DMMGamePlayerFastLauncher/issues/145#issuecomment-2501794512

**Comment by ryomaco514** [comment]
以下の通り、文字化け箇所以外大半は同じです。

Traceback (most recent call last):
  File "lib\toast.py", line 18, in _wrapper
  File "tab\account.py", line 78, in callback
  File "lib\DGPSessionV2.py", line 130, in read
sqlite3.OperationalError: Could not decode to UTF-8 column 'encrypted_value' with text 'v10T|��lk'
