### ISSUE TITLE
ショートカットの作成をした時、実行した時にエラー

### ISSUE THREAD

**Issue by jenichoe** [fa0311/DMMGamePlayerFastLauncher#151]
### OS

Windows 11

### 不具合の説明

ショートカットの作成をした時にエラーが発生し、うまく動作できないんですが。
ゲームをインストールしたフォルダーがdmmgameplayerフォルダーと違ったためでしょうか？
（dmmgameplayerはデフォルト、ゲームはF:\）

### エラーメッセージ

```Shell
ゲーム情報の取得に失敗しました。
```

### ログ

```Shell
Traceback (most recent call last):
  File "tab\shortcut.py", line 121, in fn
  File "tab\shortcut.py", line 185, in get_game_info
Exception: area not allowed
```

**Comment by fa0311** [comment]
> ゲーム情報の取得に失敗しました。
はショートカットを作成する際のアイコン情報などの取得に失敗したという意味でエラーが発生しても無視して続行します。
起動しない問題とは別の問題と思われます

> ゲームをインストールしたフォルダーがdmmgameplayerフォルダーと違ったためでしょうか？
はい
DMMGamePlayerFastLauncher は dmmgameplayer の設定ファイルを参照しそれと同じディレクトリに存在するゲームを起動しようとするためです

**Comment by fa0311** [comment]
`ゲームが存在するフォルダ` と `dmmgameplayerでインストール先と指定したフォルダ` が異なる状況がよく分からないのですが、ダウンロード先は選択できませんっけ

![image](https://github.com/user-attachments/assets/ddffbbb5-357a-40de-9d02-b1e6a66c41f9)

**Comment by jenichoe** [comment]
はいゲームを最初にダウンロードする時にダウンロード先をf:\にしてインストールしました。
アカウントのインポートとプレイヤーの高速化まではできたんですが、ショートカット作成の段階でのエラーです。
![image](https://github.com/user-attachments/assets/90238477-3e65-4b38-9a70-7df734932cf3)

**Comment by fa0311** [comment]
ホーム画面にアイコンがDMMGamePlayerFastLauncherのショートカットが出来てませんか？
ログインに失敗した際にアイコン情報などの取得に失敗しますが、ショートカットは作成されるはずです

**Comment by jenichoe** [comment]
ホーム画面にDMMGamePlayerFastLauncherのショートカットは出来てます。
ランチャーのショートカットでログインできますが、ゲームのショートカットの実行時には
エラーメッセージが出て動作しないんです。
![image](https://github.com/user-attachments/assets/3de2f72c-5f6f-429d-b96e-1201c0580a74)
![image](https://github.com/user-attachments/assets/dcedab2d-bf03-45cf-941b-49af6cfd5f75)

**Comment by fa0311** [comment]
`ショートカット` -> `GamePlayerの高速化` からランチャー起動のショートカットを作成し起動してログインし直してください

#135 を参照してください
