### ISSUE TITLE
不正な起動でエラー

### ISSUE THREAD

**Issue by hayerer** [fa0311/DMMGamePlayerFastLauncher#31]
![333](https://user-images.githubusercontent.com/39873182/170319316-e9ae4380-38a2-4efe-ad6c-57f319e34681.JPG)　どうしますか？

**Comment by fa0311** [comment]
5/27日頃にDMMGamePlayerのアップデートが配信されましたがそれでも同様のエラーが発生しますか？

**Comment by fa0311** [comment]
問題が確認できたためv4.2.2で修正しました

**Comment by hayerer** [comment]
わああ～！ほんとにありがとうございましす！！
