### ISSUE TITLE
「ログインに失敗しました」の問題

### ISSUE THREAD

**Issue by peafowl9489** [fa0311/DMMGamePlayerFastLauncher#34]
I apologize that I cannot speak Japanese well, so I can only report a bug in English.
Whenever I run the DMMGamePlayerFastLauncher, it always shows me "ログインに失敗しました". No matter I log in DMMGamePlayer or close DMMGamePlayer, it keeps showing me "ログインに失敗しました". The error message is just like the screenshot below:
![1658483491448](https://user-images.githubusercontent.com/109793672/180414429-c5d8d648-6f2c-4a39-bd6f-ca3f8314101b.jpg)

DMMGamePlayerFastLauncher version: v4.3.0 and v4.2.2
Operating system: Windows10

Thank you very much!!

**Comment by fa0311** [comment]
バグ報告ありがとうございます
この問題を再現できませんでした
DMMのアップデートによりログインの処理が変わっていたようなのでコードを修正しましたがこれでバグが直ったのかどうかは不明です
バグが修正されてないのであればこのIssueをReopenして下さい
Thanks for the bug report.
I could not reproduce this issue.
The DMM update seemed to have changed the login process, so I fixed the code, but I'm not sure if this fixes the bug or not.
If the bug has not been fixed, please reopen this Issue.

**Comment by fa0311** [comment]
releases: [v4.3.1](https://github.com/fa0311/DMMGamePlayerFastLauncher/releases/tag/v4.3.1)

**Comment by peafowl9489** [comment]
The bug is still there. But the error message seems to be a little bit different:
![1658627563857](https://user-images.githubusercontent.com/109793672/180628923-ca2a1524-e1ba-4cef-a3a8-b2233f227660.jpg)

**Comment by fa0311** [comment]
We have released [v4.5.0](https://github.com/fa0311/DMMGamePlayerFastLauncher/releases/tag/v4.5.0) which fixes this.
Please check.

**Comment by peafowl9489** [comment]
Thank you very much.
Sorry for replying so late.
