### ISSUE TITLE
リクエスト：ウィンドウサイズの設定ほしいです

### ISSUE THREAD

**Issue by justincys** [fa0311/DMMGamePlayerFastLauncher#39]
こんにちは。
「白夜極光」のウインドウサイズはフルスクリーンできません。
出来れば、ボーダーレスの設定がほしいです。
"-popupwindow -screen-width 1920 -screen-height 1080 -screen-fullscreen 0"
日本語下手です、ごめんなさい。
ありがとうございました。
---
Hello, is it possible to add window size options? I would like to request for settings for borderless windowed mode. Thank you.

**Comment by fa0311** [comment]
This will be added in v4.3.4🎉
`DMMGamePlayerFastLauncher.exe alchemystars --game-args "-popupwindow -screen-width 1920 -screen-height 1080 -screen-fullscreen 0"`
Note that it must be enclosed in `"`.

**Comment by fa0311** [comment]
Released.
[v4.4.0](https://github.com/fa0311/DMMGamePlayerFastLauncher/releases/tag/v4.4.0)
