### ISSUE TITLE
failed to authenticate device ?

### ISSUE THREAD

**Issue by negimiku** [fa0311/DMMGamePlayerFastLauncher#47]
![8cbc8a12fa2fef326d72435360732452](https://user-images.githubusercontent.com/25566752/212498025-2c7a0112-99fd-47c7-81b0-6ed718c60913.png)

ログイン出来ない状態から脱出したと思ったら、このエラーが出てゲーム起動まで行きません。
管理者権限で実行しても同じでした。

（掲示板の方にも書いてしまいました、すみません）

**Comment by fa0311** [comment]
Issueを送ってくれてありがとうございます
残念ながら再現できませんでした
以下のことを詳しく教えて貰えませんか？

- OSのバージョン (設定->システム->詳細情報から確認できます)
- システムの種類 (同上)
- プロセッサ (同上)
- 起動を試みているゲームの名前

**Comment by negimiku** [comment]
![1](https://user-images.githubusercontent.com/25566752/212527742-d9f1435f-437c-4d28-b4db-a7d70c18b127.png)
![2](https://user-images.githubusercontent.com/25566752/212527746-d8e1b6f4-a487-4924-9117-3ea1aeaf11a7.png)

PC環境は上記の通りで、DMMGamePlayerFastLauncherはv4.5.1のインストーラーで入ったexeを使用しています。
Pythonのコンパイル環境が無いもので…すみません。

試してみたゲームは、ウマ娘(umamusume)、プリコネR(priconner)、デレステ(imascgstage)で、
3つとも同じエラーで止まります。

（スロットストリート(slot)というのもあるのですが、これはそもそも対応していませんでした）

更に情報が必要でしたらなんでも言ってください。
よろしくお願いします。

**Comment by kurumigi** [comment]
以前同じエラーに遭遇しましたが、DMM GAME PLAYERの設定＞デバイス設定にある「デバイス認証」を「有料ゲームと一部基本無料ゲームでデバイス認証」に変更することで起動するようになりました。参考になると良いのですが……。

**Comment by negimiku** [comment]
情報ありがとうございます。

その設定箇所を変えて試してみたら起動出来ました！
あっちのプレイヤーのアカウント情報だけ使うと思っていたのですが、
まさか設定情報も使うとは思っていませんでした…。
これで毎回標準プレイヤーをアプリ起動後に閉じなくても済みます！

このプログラムを作ってくれたふぁさんと情報をくれたkurumigiさん、感謝です！

#ウマ娘を某60FPSにする小細工をした後から、「そのアカウント」でゲームをすると
#エリザベス女王杯オープニングアニメーションがおかしくなる…直せない…ウチだけなのかしら。

**Comment by fa0311** [comment]
次のリリースでこの問題の解決方法を表示するようにする予定です

**Comment by negimiku** [comment]
バージョンアップに向けての作業、本当にお疲れ様です。
今のところ応援しながら、有難く使用させて頂いているだけですが…。

#スロスト対応していたのですね…起動名間違ってて対応していないと勘違いしていました。
#標準プレイヤーでさえ直接起動アイコン作れなかったこのゲームが楽々起動出来て感動していますｗ
