### ISSUE TITLE
unhandled exception: Login failed エラーが出てしまいます

### ISSUE THREAD

**Issue by negimiku** [fa0311/DMMGamePlayerFastLauncher#52]
（以下、「DMMGamePlayerFastLauncher」を「FastLauncher」と略させて頂きます）

Windowsを10から11にし、FastLauncherをまた使用しようとして
DMMGamePlayer5がインストールして正常に動作する状態でFastLauncherを
以前と同じ様にインストールしました。

しかし、どうやってもFastLauncherがログイン出来ないという様なエラーになり、
どのゲームをFastLauncherから実行してもログイン出来ないとエラーが出て、
0byteのcookie.bytesが作成されます。
正常にログイン出来ていた頃はサイズが13Kbyteほどありました。

![スクリーンショット 2023-02-03 010510](https://user-images.githubusercontent.com/25566752/216394212-09aaa7f5-dec9-4376-bc46-114482b870dd.png)

DMMGamePlayer.exeは「C:\Program Files\DMMGamePlayer」、
データ類は「C:\Users\（ユーザー名）\AppData\Roaming\dmmgameplayer5」にインストールされていて、
ゲームデータ類は他のドライブにインストールしています。
バージョンは5.1.39です。

DMMGamePlayerFastLauncher.exeの場所は
「C:\Users\（ユーザー名）\AppData\Roaming\DMMGamePlayerFastLauncher」にインストールされています。
バージョンは4.6.0で、正常に起動出来ていた頃に使用していたものは1つ前の4.5.2ですが、
そのバージョンに戻してみてもダメでした。

DMMGamePlayerでログイン出来るのに何故FastLauncherでログイン出来ないのかまったく分かりません…。

よろしくお願いします。

**Comment by negimiku** [comment]
DMMGamePlayer5、ログアウトしてログインしなおしたらデバイス認証が出て1/5になりました。
しかし、やはりFastLauncherは同じエラーが出てしまいます。

DMMGamePlayerでログイン出来るのにFastLauncherでログイン出来ないのかまったく分かりません…。

**Comment by fa0311** [comment]
DMMGamePlayer [ver.5.1.39](https://player.games.dmm.com/releases/detail/cldlf4peu30yc0a19lawnnhqr/?isLatest=true) でこの不具合が発生するようです

**Comment by negimiku** [comment]
ふぁ様

お返事ありがとうございます。
DMMGamePlayerがバージョンアップしたからなのですね…。
（余計な所ばかり改悪して、使いやすい様には改良しないんですねDMMの開発）

修正版作成、よろしくお願いします。
いつも使わせて頂いて感謝しております。
