### ISSUE TITLE
ErrorCode 203

### ISSUE THREAD

**Issue by negimiku** [fa0311/DMMGamePlayerFastLauncher#54]
何度も報告してすみません。

普段使っているPCと違うPCにDMMGamePlayerFastLauncher v4.7.0をインストールして使用しようとしたのですが、
何度か純正DMMGamePlayerのインストールやデバイス認証、ゲームのインストール等でエラーを起こしながら
各タイトル（プリコネR/ウマ娘/デレステ/スロスト）が純正プレイヤーで遊べる状態にはなったのですが、
FastLauncherで以下の様なエラーが出てしまい先に進めなくなってしまいました。

![スクリーンショット 2023-02-06 212109](https://user-images.githubusercontent.com/25566752/216970748-e4020a74-b895-43c7-9fc5-e3b0cec70a07.png)

FastLauncherの説明のエラー説明を見たり、環境を変えたりしてみたのですが、行き詰まってしまいました。
純正プレイヤーのバージョンは5.1.39で、同じ構成の通常使うPCでは正常に動いているので謎です。

よろしくお願いします。

#FastLauncherのインストーラーで、インストール先を指定出来る様には出来ないでしょうか？
#純正プレイヤーでゲーム内からダウンロードされるデータがCドライブ固定なのを問い合わせたら仕様と言われました…。

**Comment by negimiku** [comment]
何故か普段使いのPCで、v4.6.0の時と同じ様な状態になってしまい、ゲーム起動が出来なくなってしまいました。

![スクリーンショット 2023-02-06 222101](https://user-images.githubusercontent.com/25566752/216982499-92d2e4e5-8de7-49fe-b242-b95d9d6096dd.png)

使っているFastLauncherは間違いなくv4.7.0なのですが…こちらの環境のせいでしょうか？

**Comment by fa0311** [comment]
DMMGamePlayer ver.5.1.39 自体がとても不安定みたいです
ErrorCode 203 はDMMサーバ側のセッション管理がうまくいってないために発生すると考えています
実際、DMMGamePlayer 1.5.39 は頻繁に再ログインを求められるますね

**Comment by fa0311** [comment]
関係あるかわかりませんが #56 を修正しました

**Comment by negimiku** [comment]
改悪大好きですねDMM…サポートの対応も改悪されていますし。

修正ソースで.exe作成コンパイルしたいですが、まだ勉強していません…後で調べてみます。
この修正だけでコンパイル済.exe上げてもらうのも申し訳ありませんので…。

**Comment by ryomaco514** [comment]
お疲れ様です。
当方では昨日まで問題なかったのですがDMMPlayer5.1.40以降同様の事象が発生しています。
内容は以下のとおりです。ご確認のほどよろしくお願いいたします。
![image](https://user-images.githubusercontent.com/16443895/218236977-8f595109-ea7e-4d7e-ab0e-ed93b9ab041c.png)

**Comment by fa0311** [comment]
DMMGamePlayer [ver.5.2.0](https://player.games.dmm.com/releases/detail/clf95mmyk1cjs0bztu4ib9mey/) がリリースされ DMMGamePlayerFastLauncher [v4.8.0](https://github.com/fa0311/DMMGamePlayerFastLauncher/releases/tag/v4.8.0) をリリースしたので閉じます
新たに問題が発生した場合は新たに[issues](https://github.com/fa0311/DMMGamePlayerFastLauncher/issues/new)を立ててください
