### ISSUE TITLE
DMMGamePlayer ver.5.1.39 が不安定

### ISSUE THREAD

**Issue by fa0311** [fa0311/DMMGamePlayerFastLauncher#55]
おいDMM
- Cookieの暗号化 #52
- ErrorCode 203 #54
- リダイレクト先のリンク #56

**Comment by negimiku** [comment]
v4.7.1、試してみましたが、特に何か状態が良くなった…というのはありませんでした。

純正プレイヤーを立ち上げたり終了させたり、色々ゲーム立ち上げたり終了したりしたタイミングで
FastLauncher（でゲーム）を起動させたりすると、たまにうまく起動したりする状態です。
（1度起動出来るとしばらくどのゲームもFastLauncherで起動出来る状態になり、
ダメになると203ではない「ログイン出来ない」という、いつものエラーが出続けます）

たまに起動出来るというのが厄介…というか、純正プレイヤーが一体どこが純正なんだか。
改悪が好きなんですかね？ それともこのFastLauncher対策とかだったりするのでしょうか？
だとしたら、先におウマさんで大活躍中のversion.dll対策をすると思いますがｗ

**Comment by fa0311** [comment]
純正プレイヤーを立ち上げた際に自動ログインにチェックを付けたのにも関わらずログインを求められませんか？
もし求められるのであれば純正プレイヤー(もしくはサーバー)のバグでそれが改善されるまで使うのは厳しいかもです
v4.7.0をアップロードした時点では何も問題なく動いていたのでDMMのサーバー側の問題だとは思いますが待ってみるしかないです

FastLauncher対策は可能性としてはあるかもしれません
今回のアプデでログインの処理に必要なデータが暗号化されていてより複雑な動作を求められるようになって対応に時間がかかりました
(ウェーイ！DMMくん見てるー？)

version.dll はサイゲ側の問題なのでDMMにはどうすることも出来ないです

**Comment by negimiku** [comment]
今のところ、純正プレイヤーから何かゲームを1つ起動して、終了後からならFastLauncherが使えますね。
何かのタイミングでログイン出来ないエラーが出る様になってしまいますが。
今回の純正5.1.40で何が修正されたのか分かりませんが…。

**Comment by ryomaco514** [comment]
> 今のところ、純正プレイヤーから何かゲームを1つ起動して、終了後からならFastLauncherが使えますね。 何かのタイミングでログイン出来ないエラーが出る様になってしまいますが。 今回の純正5.1.40で何が修正されたのか分かりませんが…。

はじめまして。
私の方では5.1.40で今日はじめて発症し、いずれかゲームを起動してから終了を行っても同じエラーが起きるようでした。

**Comment by fa0311** [comment]
DMMGamePlayerを起動している間にFastLauncherを起動するとほぼ必ずログインのエラーが出るようです
また、DMMGamePlayerを終了して10秒以内(要検証)にFastLauncherを起動するとログインのエラーが出るようです
ちなみに、ログインエラーが発生しても数時間以内にFastLauncherの起動に成功していれば`cookie.bytes`にキャッシュをしているためログインできます
ErrorCode 203はそのキャッシュが古いために発生するエラーです

**Comment by fa0311** [comment]
DMMGamePlayer [ver.5.2.0](https://player.games.dmm.com/releases/detail/clf95mmyk1cjs0bztu4ib9mey/) がリリースされ DMMGamePlayerFastLauncher [v4.8.0](https://github.com/fa0311/DMMGamePlayerFastLauncher/releases/tag/v4.8.0) をリリースしたので閉じます
新たに問題が発生した場合は新たに[issues](https://github.com/fa0311/DMMGamePlayerFastLauncher/issues/new)を立ててください
