### ISSUE TITLE
unhandled exception in script

### ISSUE THREAD

**Issue by wrandifan** [fa0311/DMMGamePlayerFastLauncher#61]
![image](https://user-images.githubusercontent.com/17224332/227045838-5f6a1daf-2967-4a1e-89e2-f612a999227a.png)

**Comment by fa0311** [comment]
This may be a duplicate of #60.
Is it possible to install and run [v4.9.0](https://github.com/fa0311/DMMGamePlayerFastLauncher/releases/tag/v4.9.0)
