### ISSUE TITLE
Windows Defenderに検疫される

### ISSUE THREAD

**Issue by kotobukit** [fa0311/DMMGamePlayerFastLauncher#63]
いつも快適に利用させていただいています。
v4.9.0でWindows Defenderにより検疫されてしまったのでとりあえず報告させていただきます。

![スクリーンショット 2023-04-16 215644](https://user-images.githubusercontent.com/46299983/232313331-8edff0d0-cf35-4bbb-bb2b-d5957bd1f16a.png)

> Windows 10 Pro 22H2
> OSビルド 19045.2846
> Windows Feature Experience Pack 120.2212.3530.0

**Comment by fa0311** [comment]
使用しているpyinstallerというツールがウイルスの制作によく利用されていることに起因する誤検知です
(pyinstaller自体に悪意は無いし当然このツールにも悪意はありません)

これに関して具体的な回避策が無いので以下の操作を行って復元してください

![](https://raw.githubusercontent.com/fa0311/DMMGamePlayerFastLauncher/master/docs/img/windows_defender1.png)
![](https://raw.githubusercontent.com/fa0311/DMMGamePlayerFastLauncher/master/docs/img/windows_defender2.png)

**Comment by kotobukit** [comment]
返信ありがとうございます。
pyinstallerに起因するとのことで理解しました。
問題ないことが確認できましたのでクローズとさせていただきます。
