### ISSUE TITLE
UAC自動昇格のオプションが使えない。(force-bypass-uac)

### ISSUE THREAD

**Issue by reindex-ot** [fa0311/DMMGamePlayerFastLauncher#69]
自動昇格のオプションを加えてもタスクスケジューラーのUACが表示され、許可を選択したとしてもゲーム自体が起動しません。現状ではツールによるUACの自動昇格のショートカットを生成でゲームタイトルの引数を加えてショートカットを生成する事で使えている状態です。(WinaeroTweakerの昇格ショートカット生成機能)

OS: Windows11 Pro 22H2
CPU: Intel Xeon E5-2650v4
メモリ: 32GB

...の環境下で使っています。

![IMG_20230610_084234](https://github.com/fa0311/DMMGamePlayerFastLauncher/assets/32851879/f4ba1795-9c36-459d-8c46-46254a5a5c89)

**Comment by fa0311** [comment]
何点か追加で聞きたいことがあります
- DMMの公式ランチャーのインストール先ディレクトリ
- 本ツールのインストール先ディレクトリ

**Comment by reindex-ot** [comment]
各アプリケーションのインストール先は
- DMMGamePlayer
`C:\Program Files\DMMGamePlayer`
- DMMGamePlayerFastLauncher
`C:\Users\ユーザー名\AppData\Roaming\DMMGamePlayerFastLauncher`

と通常な配置にしています。ストレージの変更やパスの変更は行なっていません。
