### ISSUE TITLE
v5.0のアカウントのインポート

### ISSUE THREAD

**Issue by reindex-ot** [fa0311/DMMGamePlayerFastLauncher#79]
'DMMGamePlayerFastLauncher\data\account'にCookies.bytesを移動させないとアカウント情報が表示されない。
DMMGamePlayerに格納された物をインポートさせるようにして欲しい。

**Comment by fa0311** [comment]
DMMGamePlayer にログインした状態でここからインポートできると思います
ファイル名には分かりやすい任意の名前を付けてください (説明が不足していたので修正予定)

![image](https://github.com/fa0311/DMMGamePlayerFastLauncher/assets/34892635/8407c35d-be5d-453d-9de9-7a2c34f665b5)
