### ISSUE TITLE
アイコン

### ISSUE THREAD

**Issue by fa0311** [fa0311/DMMGamePlayerFastLauncher#8]
PyinstallerやInno Setupのアイコンのままなので変えたい

**Comment by reindex-ot** [comment]
アイコン作りました。
UACの自動昇格が上手くできない場合の方法も作りました。
代用で管理者権限のショートカットを作成するノでも同じ事がやれると思います。
https://note.com/reindex/n/nb0d972bcf0d6
![DMMFast](https://github.com/fa0311/DMMGamePlayerFastLauncher/assets/32851879/bb60a85f-f633-4fec-9c24-e042cfaab383)

**Comment by reindex-ot** [comment]
DMMのロゴがアレなんで別パターンも作成。
![Icon2](https://github.com/fa0311/DMMGamePlayerFastLauncher/assets/32851879/a8830c7f-7f16-4250-a0e8-db2f7e295050)

**Comment by fa0311** [comment]
> ![DMMFast](https://user-images.githubusercontent.com/32851879/244580804-bb60a85f-f633-4fec-9c24-e042cfaab383.png)

ありがとうございます！めちゃくちゃ助かります！

このDマークは公式ランチャーのものをそのまま流用していますか？
それともそれに似ている別のものですか？

公式ランチャーの流用はまずいのでそこだけ確認したいです

**Comment by fa0311** [comment]
UACの自動昇格が上手くできない問題は修正したいので新しくissueを開いて詳しく環境を教えて貰えますか？

**Comment by reindex-ot** [comment]
このDは公式から切り抜いた奴なんで権利的にアレならボツでOKです。

**Comment by fa0311** [comment]
ありがとうございます！
