### ISSUE TITLE
有料PCゲームの起動に対応する予定はありますか？

### ISSUE THREAD

**Issue by kotobukit** [fa0311/DMMGamePlayerFastLauncher#87]
バージョンが上がってからも快適に利用させていただいています。

DMMGamePlayer Fast Launcherは主にソーシャルゲームのPC版の起動に関して取り扱っていると思いますが、
DMMGamePlayerから起動が必要な有料PCゲームに対応する予定はありますか？

以下のゲーム等、product_idが `gp_<8桁英数小文字>`のものになります。
https://dlsoft.dmm.co.jp/detail/clear_0019/

現状では、**v.5.0.1**にて以下のようなログがでてショートカットの作成に失敗します
```
Traceback (most recent call last):
  File "lib\toast.py", line 17, in _wrapper
  File "tab\shortcut.py", line 115, in save_callback
  File "tab\shortcut.py", line 133, in get_game_info
Exception: app not exists
```
ランチャーのショートカットを作成し、ランチャーを起動してからであれば
ゲームが起動できるのでプレイするだけなら支障はありません。

必要であればデバッグウィンドウの内容を添付できます。

issueは一通り見たつもりですが、重複していた場合はクローズしていただいて構いません。

よろしくお願いいたします。

**Comment by fa0311** [comment]
アダルトゲームの体験版で再現できた
より具体的には内部の gameType が AMAIN のゲームが起動できない

**Comment by fa0311** [comment]
DRMで保護されたゲームの起動に関して次のアップデートで対応予定です
