### ISSUE TITLE
ゲームを終了した際にUnicodeDecodeErrorになる

### ISSUE THREAD

**Issue by kotobukit** [fa0311/DMMGamePlayerFastLauncher#98]
### OS

Windows10 22H2

### 不具合の説明

#87 の対応ありがとうございました。
手持ちのゲームも生成したショートカット経由で起動できています。

1点、**v5.1.2**にて、DRMで保護されたゲームを終了した際にUnicodeDecodeErrorが発生しました。
対象のゲームは前回と同様こちらとなります。
https://dlsoft.dmm.co.jp/detail/clear_0019/

ウマ娘やデレステ等ではこの事象は発生しません。
DMMGamePlayerで起動する必要のある積んでいたゲームや体験版等をインストールして、同様の事象が起きるか検証しましたが、
そもそも起動しない等が発生したので今のところ他のゲームでは再現できていません。

### エラーメッセージ

```Shell
Traceback (most recent call last):
  File "launch.py", line 41, in thread
  File "launch.py", line 94, in launch
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8f in position 0: invalid start byte
```

**Comment by fa0311** [comment]
報告ありがとうございます
このエラーはログ出力に関するもので悪影響はないと思いますが次のアップデートで修正します

> そもそも起動しない等が発生したので今のところ他のゲームでは再現できていません。

別のissuesを立てて詳しく報告できますか？
